"""API router package — registers all route modules."""

from app.api import (
    auth,
    reports,
    issues,
    work_orders,
    users,
    departments,
    analytics,
    notifications,
    search,
    ai_assistant,
    assets,
    service_requests,
    inspections,
    sla,
    crews,
    equipment,
    assignments,
    risk,
    preventive,
    gis,
    transparency,
    jurisdictions,
)

__all__ = [
    "auth",
    "reports",
    "issues",
    "work_orders",
    "users",
    "departments",
    "analytics",
    "notifications",
    "search",
    "ai_assistant",
    "assets",
    "service_requests",
    "inspections",
    "sla",
    "crews",
    "equipment",
    "assignments",
    "risk",
    "preventive",
    "gis",
    "transparency",
    "jurisdictions",
]
